Com:
  TechDivision:
    Neos:
      Search:
        ServerData:
          hostname: 'localhost'
          port: 8983
        # defines the schema for solr
        Schema:
          # The field which defines the uniqueKey
          DocumentIdentifierField: 'id'
          # default boost for the document
          DocumentDefaultBoost: 1.0
          # default boost for fields
          FieldDefaultBoost: 1.0
          ContentTypes:
            # Add here every contentType with their properties which should get indexed by solr
            # The boosts(float) are optional, fallback is the DefaultDocumentBoost or DefaultFieldBoost
            # The fieldName gets configured in the next section.
            #
            # Example:
            #
            # My.Awesome.Content:Type:
            #   documentBoost: 1.2
            #   properties:
            #     property1:
            #       fieldName: 'field123'
            #       fieldBoost: 1.5
            #     otherProperty:
            #       fieldName: 'field124'
            #
            #
            TYPO3.Neos.ContentTypes:Text:
              documentBoost: 1.0
              properties:
                text:
                  fieldName: 'field2'
                  fieldBoost: 1
            TYPO3.Neos.ContentTypes:Headline:
              properties:
                title:
                  fieldName: 'field1'
                  fieldBoost: 1
            TYPO3.Neos.ContentTypes:Page:
              properties:
                title:
                  fieldName: 'field1'
            TYPO3.Neos.ContentTypes:Shortcut:
              properties:
                title:
                  fieldName: 'field1'
          # Defines the fieldNames of the solr scheme
          FieldNames:
            field1: 'subject'
            field2: 'description'